"""Secret provider abstractions and fail-closed secret validation.

The application only depends on :class:`SecretProvider`.  The default
implementation reads process environment variables, while deployments may
provide an adapter for their own secret manager without changing application
code.
"""

from __future__ import annotations

import os
from abc import ABC, abstractmethod
from collections.abc import Mapping


class SecretValidationError(ValueError):
    """Raised when a required secret is absent or unsafe for its environment."""


# Values commonly copied from examples or generated by scaffolding tools.  The
# comparison is case-insensitive and ignores surrounding whitespace.
DEMO_SECRET_VALUES = frozenset(
    {
        "change-me",
        "change_me",
        "changeme",
        "secret",
        "dev-secret",
        "dev_secret",
        "test-secret",
        "test_secret",
        "password",
        "password123",
        "changethisdemopassword!123",
        "your-secret-here",
        "your_secret_here",
    }
)


class SecretProvider(ABC):
    """Interface used to retrieve application secrets.

    Providers must return ``None`` when a key is unavailable and must never
    log, transform, or expose secret values.  ``get_required`` centralizes
    fail-closed validation for all providers.
    """

    @abstractmethod
    def get(self, name: str) -> str | None:
        """Return a secret by name, or ``None`` when it is unavailable."""

    def get_required(
        self,
        name: str,
        *,
        environment: str = "development",
        min_length: int = 1,
        reject_demo: bool = False,
    ) -> str:
        """Return and validate a required secret without revealing its value."""

        value = self.get(name)
        return validate_secret(
            name,
            value,
            environment=environment,
            min_length=min_length,
            reject_demo=reject_demo,
        )


class EnvironmentSecretProvider(SecretProvider):
    """Read secrets from an environment-like mapping (``os.environ`` by default)."""

    def __init__(self, environ: Mapping[str, str] | None = None):
        self._environ = os.environ if environ is None else environ

    def get(self, name: str) -> str | None:
        return self._environ.get(name)


def validate_secret(
    name: str,
    value: str | None,
    *,
    environment: str = "development",
    min_length: int = 1,
    reject_demo: bool = False,
) -> str:
    """Validate a secret and return it unchanged.

    Required values are rejected when missing or blank.  Demo values are
    always rejected when ``reject_demo`` is true, and automatically rejected
    in production.  Secret contents are intentionally excluded from errors.
    """

    if not name or not name.strip():
        raise SecretValidationError("Secret name is required")
    if min_length < 1:
        raise ValueError("min_length must be at least 1")
    if value is None or not value.strip():
        raise SecretValidationError(f"{name} is required")
    if len(value) < min_length:
        raise SecretValidationError(f"{name} must be at least {min_length} characters")
    normalized = value.strip().lower()
    if (reject_demo or environment == "production") and normalized in DEMO_SECRET_VALUES:
        raise SecretValidationError(f"{name} must not use a demo value")
    return value

